### ISSUE TITLE
Fraud Detection will mess you up

### ISSUE THREAD

**Issue by AltayAkkus** [philippnormann/nvidia-sniper#74] opened 2020-10-13 09:00 UTC
I really liked this repository, but I am concerned that automated payment via Browser Automation will trigger Paypals Fraud Detection and will mess up your day.

**Comment by philippnormann** [comment] 2020-10-27 14:11
Not sure about PayPal fraud detection, but buying through the Nvidia store using the guest checkout (credit card) is working without any issues. During the last drop, multiple people (approx. 50 confirmed via Discord) got their cards using this bot. Unless you get your order canceled due to using this bot, I will close this issue for now since it is only based on speculation.

**Closed by philippnormann** 2020-10-27 14:11 UTC
